// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7eogfFwVgb_IcJQ_FGtYYOfe5nUSjGGQ',
    appId: '1:521051837726:android:7eabed46b104923028250f',
    messagingSenderId: '521051837726',
    projectId: 'react-my-burger-baf73',
    databaseURL: 'https://react-my-burger-baf73.firebaseio.com',
    storageBucket: 'react-my-burger-baf73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC00rMNjJSvXdrmaQFKsrPUajtjdXOvONY',
    appId: '1:521051837726:ios:935adacf37ba07cc28250f',
    messagingSenderId: '521051837726',
    projectId: 'react-my-burger-baf73',
    databaseURL: 'https://react-my-burger-baf73.firebaseio.com',
    storageBucket: 'react-my-burger-baf73.appspot.com',
    iosClientId: '521051837726-j7cebjs9r67q5jhmn1fd05vopthca8s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.boxcricket.boxCricket',
  );
}
